# Generated by Django 3.2 on 2023-04-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='아이디')),
                ('user_pw', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('user_name', models.CharField(max_length=16, unique=True, verbose_name='이름')),
                ('user_email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('user_birth', models.DateTimeField(auto_now_add=True, verbose_name='생일')),
                ('user_role', models.CharField(max_length=4, verbose_name='역할')),
                ('user_phone', models.CharField(max_length=11, unique=True, verbose_name='전화번호')),
                ('user_school', models.CharField(max_length=32, verbose_name='학교')),
            ],
        ),
    ]
